name: Build Development

on:
  workflow_dispatch:
  push:
    branches:
      - "v**"
      - main
    paths:
      - "src/**"
      - "mod.json"
      - "CMakeLists.txt"
      - ".github/workflows/uwu.yml"
  pull_request:
    branches:
      - "v**"
      - "main"
    paths:
      - "src/**"
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: qm7dev/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}
          sdk: nightly
          
          
  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build iOS
        uses: geode-catgirls/build-geode-mod@main
        with:
          bindings: kingminer7/bindings
          target: iOS
          gh-pat: ${{ secrets.GH_PAT }}
          combine: true
          # super secret
          
  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build', 'build-ios']

    steps:
      - uses: geode-catgirls/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
